#!/usr/bin/env bash
#Write a Bash script that displays:the content of the current directory in a list format. Where only the part of the name after the first dash is displayed
for FILE in *
do
	echo "$FILE" | cut -d - -f2,3
done
